### ISSUE TITLE
The module does not seem to support the 3.2 client

### ISSUE THREAD

**Issue by simo8102** [YuukiPS/Launcher-Android#4]
The module does not seem to support the 3.2 client

**Comment by akbaryahya** [comment]
This method won't work anymore, because it's just a proxy not a GAME PATCH and for the game patch to work you have to patch `libil2cpp.so` with the public key sig key GC and unfortunately now no one has shared the libil2cpp.so that was already in modify with the GC key so please do an experiment if you can edit libil2cpp.so good luck
